#!/usr/bin/env bash

function help {
  echo cluster commander - matdulgi
  echo 'clcmd <subCommand>'
  echo '# sub command'
  echo    -scp
  echo    -cmd
  echo    -apnd
  echo    -help, -h
}


function init {
  clcmd_home=$(cd $(dirname $0) && pwd)
  clcmd_conf=$clcmd_home/clcmd.conf

  nodes=$(cat $clcmd_conf | grep ^\s*nodes | cut -d'=' -f2)
  curNode=$(cat $clcmd_conf | grep ^\s*curNode | cut -d'=' -f2)

#if [[ -z $curNode ]]; then
#  curNode=$(hostname -a)
# hostname -a is deprecated
#fi
  echo node list : $nodes
  echo current node : $curNode
}


function getTargetHome {
  ssh $1 'echo $HOME'
}

function clcmd {
  if [ -z $2 ] ; then
    echo no command
    exit
  fi

  argArr=( $@ )
  cmd=${argArr[@]:1}
#  echo command : $cmd

  for node in $nodes; do
#   eval ssh $node $cmd
    echo  \$ $node : $cmd 
    ssh $node $cmd
    echo $node done
  done;    
  echo 
}

function clscp {
  orgPath=$2
  destPath=""
  recursive=""

  #verify file path
  if [ -z $orgPath ];then
    echo there\'s no file
    exit
  else
    if [ -d $orgPath ];then
      echo is directory : 'true'
      recursive='-r'
    elif [ -f $orgPath ];then    
      recursive=""
    fi
  fi

  if [ -z $orgPath ]; then
    echo 'no origin file path definitnion' 
    exit
  fi

  for node in $nodes; do
    if [ "$node" != "$curNode" ];then
      remoteHome=$(ssh $node 'echo $HOME')
#      destPath=$(echo $3 | sed "s|^${HOME}|~|")

#  if [ -z $destPath ]; then
#    destPath=$(cd $(dirname $orgPath) && pwd | sed "s|^$HOME|~|")
#  else
      destPath=$(echo $3 |  sed "s|^${HOME}|${remoteHome}|")
#  fi

      echo "cp $orgPath -> ${node}:${destPath}"
      scp -F ~/.ssh/config $recursive $orgPath ${node}:${destPath}
    fi
  done;    
}

function clapnd {
  appendText=""

#  echo origin path : $appendFilePath

  if [ -z $2 ];then
    echo no appendFile declared
    exit
  fi
  if [ -d $2 ];then
    echo appendFile declared is directory
    exit
  fi
  if [ -f $2 ]; then
    echo append type : file
    appendText=$(cat $2)
  else
    echo append type : text
  fi
  if [ -z $3 ];then
    echo no target File
    exit
  fi
  
  echo append text : $appendText

  for node in ${nodes[@]}; do
    if [ "$node" != "$curNode" ];then
      targetPath=$(echo $3 |  sed "s|^${HOME}|${remoteHome}|")
      echo "append $appendText -> ${node}:${targetPath}"
      ssh ${node} "echo $appendText >> ${targetPath}"
      echo $node appended
    fi
  done;    
}

init $@

case $1 in 
  -c)
    clcmd $@
    ;;
  -s)
    clscp $@
    ;;
  -a)
    clapnd $@
    ;;
  -h) 
    help
    ;;
  *) 
    help
    exit
    ;;
esac
